import { ELECTION_2025, PARTIES, POLITICIANS, TOPICS, partyByName, topicByName } from "../data/reference";
import type {
  Coverage, Headline, PartyTopicLink, SourceRef, TimelineEvent, Totals, WeeklySeries,
} from "../types";

/**
 * Media-monitor data service. Today it reads a snapshot exported from the monitor's Supabase database
 * (src/data/snapshot.json, regenerated by scripts/export_snapshot.py). A live implementation only has to return the
 * same MonitorData shape, so pages and components do not change.
 */

interface RawSeries { n: number[]; pos: number[]; neg: number[] }
interface RawSnapshot {
  generated: string;
  weeks: string[];
  total_weekly: number[];
  party: Record<string, RawSeries>;
  issue: Record<string, RawSeries>;
  party_totals: { name: string; n: number; pos: number; neg: number; social: number }[];
  issue_totals: { name: string; n: number; pos: number; neg: number; social: number }[];
  matrix: { party: string; issue: string; n: number }[];
  platforms: { platform: string; n: number }[];
  totals: { items: number; first_day: string; last_item: string; ai: number; sources: number; with_party: number; with_issue: number };
  headlines: { k: "party" | "issue"; name: string; title: string; source: string; platform: string; d: string; url: string; sentiment?: string }[];
  politicians: { weekly: Record<string, number[]>; recent: { name: string; title: string; source: string; platform: string; d: string; url: string }[] };
  peaks: { d: string; wk: string; title: string; source: string; platform: string; url: string; parties: string[]; issues: string[]; r: number }[];
}

export interface MonitorData {
  totals: Totals;
  weeks: string[];
  /** Index of the last week, which is still running when the snapshot is taken. */
  partialWeek: number;
  /** Days of the running week covered by the snapshot (1 to 7). */
  partialDays: number;
  total: number[];
  party: Map<string, Coverage>;
  topic: Map<string, Coverage>;
  politician: Map<string, { weekly: number[]; headlines: Headline[] }>;
  links: PartyTopicLink[];
  events: TimelineEvent[];
  headlines: (Headline & { entity: { kind: "party" | "topic"; id: string } })[];
}

export const MONITOR_SOURCE: SourceRef = {
  name: "Politiek Monitor: nieuws en sociale media (Google News, nieuwssites, GDELT, Mastodon, YouTube, Reddit)",
  verification: "verified",
};

const empty = (len: number) => Array.from({ length: len }, () => 0);

function toHeadline(h: { title: string; source: string; platform: string; d: string; url: string; sentiment?: string }): Headline {
  return { title: h.title, source: h.source, platform: h.platform, date: h.d, url: h.url,
    sentiment: h.sentiment as Headline["sentiment"] };
}

function build(raw: RawSnapshot): MonitorData {
  const weeks = raw.weeks;
  const len = weeks.length;
  const series = (s?: RawSeries): WeeklySeries =>
    ({ weeks, n: s?.n ?? empty(len), pos: s?.pos ?? empty(len), neg: s?.neg ?? empty(len) });

  const headlines = raw.headlines.map((h) => {
    const entity = h.k === "party"
      ? { kind: "party" as const, id: partyByName.get(h.name)?.id ?? h.name }
      : { kind: "topic" as const, id: topicByName.get(h.name)?.id ?? h.name };
    return { ...toHeadline(h), entity };
  });

  const party = new Map<string, Coverage>();
  for (const p of PARTIES) {
    const t = raw.party_totals.find((x) => x.name === p.name) ?? { n: 0, pos: 0, neg: 0, social: 0 };
    party.set(p.id, { series: series(raw.party[p.name]), totals: t,
      headlines: headlines.filter((h) => h.entity.kind === "party" && h.entity.id === p.id) });
  }
  const topic = new Map<string, Coverage>();
  for (const tp of TOPICS) {
    const t = raw.issue_totals.find((x) => x.name === tp.name) ?? { n: 0, pos: 0, neg: 0, social: 0 };
    topic.set(tp.id, { series: series(raw.issue[tp.name]), totals: t,
      headlines: headlines.filter((h) => h.entity.kind === "topic" && h.entity.id === tp.id) });
  }
  const politician = new Map<string, { weekly: number[]; headlines: Headline[] }>();
  for (const pol of POLITICIANS) {
    politician.set(pol.id, {
      weekly: raw.politicians.weekly[pol.name] ?? empty(len),
      headlines: raw.politicians.recent.filter((h) => h.name === pol.name).map(toHeadline),
    });
  }

  const links: PartyTopicLink[] = raw.matrix
    .filter((m) => partyByName.has(m.party) && topicByName.has(m.issue))
    .map((m) => ({ party: partyByName.get(m.party)!.id, topic: topicByName.get(m.issue)!.id, n: m.n }));

  const lastWeekStart = new Date(weeks[len - 1]);
  const generated = new Date(raw.generated);
  const elapsed = (generated.getTime() - lastWeekStart.getTime()) / 86_400_000;
  const partialWeek = elapsed < 7 ? len - 1 : len;
  const partialDays = Math.min(7, Math.max(1, Math.floor(elapsed) + 1));

  return {
    totals: {
      items: raw.totals.items, firstDay: raw.totals.first_day, lastItem: raw.totals.last_item, ai: raw.totals.ai,
      sources: raw.totals.sources, withParty: raw.totals.with_party, withTopic: raw.totals.with_issue,
      platforms: raw.platforms, generated: raw.generated,
    },
    weeks, partialWeek, partialDays, total: raw.total_weekly, party, topic, politician, links,
    events: buildEvents(raw), headlines,
  };
}

/** Timeline: reference events (with their official source) plus the busiest weeks in the monitor, each with the
 * headlines that defined it. The busiest weeks are data, not editorial judgement: they are ranked by item count. */
function buildEvents(raw: RawSnapshot): TimelineEvent[] {
  const reference: TimelineEvent[] = [
    { id: "tk2025", date: "2025-10-29", kind: "election", title: "Tweede Kamerverkiezing",
      summary: "Verkiezing van de 150 leden van de Tweede Kamer.", parties: [], topics: ["kabinet-formatie"],
      sources: [ELECTION_2025], layer: "fact" },
    { id: "gr2026", date: "2026-03-18", kind: "election", title: "Gemeenteraadsverkiezingen",
      summary: "Verkiezing van de gemeenteraden in heel Nederland.", parties: [], topics: [],
      sources: [{ name: "Kiesraad: gemeenteraadsverkiezingen 2026", url: "https://www.kiesraad.nl/verkiezingen/gemeenteraden",
        verification: "unverified" }], layer: "fact" },
  ];
  const byWeek = new Map<string, RawSnapshot["peaks"]>();
  for (const p of raw.peaks) byWeek.set(p.wk, [...(byWeek.get(p.wk) ?? []), p]);
  const peaks: TimelineEvent[] = [...byWeek.entries()].map(([wk, items]) => {
    items.sort((a, b) => a.r - b.r);
    const lead = items[0];
    return {
      id: `peak-${wk}`, date: wk, kind: "media-peak", title: lead.title,
      parties: [...new Set(items.flatMap((i) => i.parties))].map((n) => partyByName.get(n)?.id).filter(Boolean) as string[],
      topics: [...new Set(items.flatMap((i) => i.issues))].map((n) => topicByName.get(n)?.id).filter(Boolean) as string[],
      sources: items.map((i) => ({ name: i.source, url: i.url, published: i.d, verification: "verified" as const, note: i.title })),
      layer: "data",
    };
  });
  return [...reference, ...peaks].sort((a, b) => a.date.localeCompare(b.date));
}

let cache: Promise<MonitorData> | null = null;

/** Loads the snapshot once (as its own chunk, so the first paint does not wait for it). */
export function loadMonitor(): Promise<MonitorData> {
  cache ??= import("../data/snapshot.json").then((m) => build(m.default as unknown as RawSnapshot));
  return cache;
}
